if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required.")
endif()

if(NOT DEFINED BINARY_DIR)
    message(FATAL_ERROR "BINARY_DIR is required.")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required.")
endif()

set(_presets_file "${SOURCE_DIR}/CMakePresets.json")
if(NOT EXISTS "${_presets_file}")
    message(FATAL_ERROR "CMakePresets.json was not found at '${_presets_file}'.")
endif()

file(READ "${_presets_file}" _presets_json)

function(idtech4_append_visible_presets out_var heading array_name)
    set(_text "## ${heading}\n\n")
    string(JSON _count ERROR_VARIABLE _count_error LENGTH "${_presets_json}" "${array_name}")
    if(_count_error)
        string(APPEND _text "_No ${heading} are defined._\n\n")
        set(${out_var}
            "${${out_var}}${_text}"
            PARENT_SCOPE
        )
        return()
    endif()

    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
        string(
            JSON
            _name
            GET
            "${_presets_json}"
            "${array_name}"
            ${_index}
            name
        )
        string(
            JSON
            _hidden
            ERROR_VARIABLE
            _hidden_error
            GET
            "${_presets_json}"
            "${array_name}"
            ${_index}
            hidden
        )
        if(NOT _hidden_error AND _hidden)
            continue()
        endif()

        string(
            JSON
            _display
            ERROR_VARIABLE
            _display_error
            GET
            "${_presets_json}"
            "${array_name}"
            ${_index}
            displayName
        )
        if(_display_error)
            set(_display "${_name}")
        endif()

        string(APPEND _text "- `${_name}` - ${_display}\n")
    endforeach()

    string(APPEND _text "\n")
    set(${out_var}
        "${${out_var}}${_text}"
        PARENT_SCOPE
    )
endfunction()

string(TIMESTAMP _generated_at "%Y-%m-%dT%H:%M:%SZ" UTC)

set(_doc "# IdTech4 Remaster Build System\n\n")
string(APPEND _doc "Generated by `idtech4_generate_docs` at `${_generated_at}`.\n\n")
string(APPEND _doc "Source tree: `${SOURCE_DIR}`\n\n")
string(APPEND _doc "Build tree: `${BINARY_DIR}`\n\n")
string(
    APPEND
    _doc
    "The modern CMake entrypoints are target-based and are intended to be driven through presets. CI uses the same presets listed below so local and hosted builds stay reproducible.\n\n"
)

idtech4_append_visible_presets(_doc "Configure Presets" configurePresets)
idtech4_append_visible_presets(_doc "Build Presets" buildPresets)
idtech4_append_visible_presets(_doc "Test Presets" testPresets)

string(APPEND _doc "## Dependency Management\n\n")
string(
    APPEND
    _doc
    "- CPM.cmake is pinned and bootstrapped by `cmake/IdTech4Dependencies.cmake` for header-only and lightweight dependencies.\n"
)
string(
    APPEND
    _doc
    "- FetchContent remains the provider for small source dependencies that should be built directly with the current tree.\n"
)
string(
    APPEND
    _doc
    "- vcpkg is the provider for large optional dependencies through `vcpkg.json` and the `ninja-vcpkg-*` presets; the `large-audio` feature currently resolves `openal-soft`.\n"
)
string(
    APPEND
    _doc
    "- `IDTECH4_DEPENDENCY_DOWNLOADS=OFF` can be used with a warmed dependency cache to prevent configure-time downloads.\n\n"
)

string(APPEND _doc "## Build Acceleration And Size Analysis\n\n")
string(APPEND _doc "- `IDTECH4_ENABLE_UNITY_BUILDS=ON` enables CMake unity builds per target.\n")
string(
    APPEND
    _doc
    "- `IDTECH4_ENABLE_PRECOMPILED_HEADERS=ON` enables the legacy engine PCH for C++ engine targets while lightweight test targets opt out.\n"
)
string(
    APPEND
    _doc
    "- `IDTECH4_ENABLE_BUILD_CACHE=ON`, `IDTECH4_ENABLE_CCACHE=ON`, and `IDTECH4_ENABLE_SCCACHE=ON` attach compiler launchers as target properties when the tool is available.\n"
)
string(
    APPEND
    _doc
    "- `IDTECH4_ENABLE_FAST_ITERATION=ON` bundles unity builds, precompiled headers, and compiler-cache launcher support for local edit/build loops.\n"
)
string(APPEND _doc "- `IDTECH4_ENABLE_LTO=ON` enables target IPO/LTO when the active toolchain supports it.\n")
string(APPEND _doc
       "- `idtech4_binary_size` writes `reports/binary-size.md` with byte and MiB totals for built artifacts.\n\n"
)

string(APPEND _doc "## Windows Batch Entrypoints\n\n")
string(APPEND _doc "- `setup_ev.bat` prepares the Visual Studio 2026 developer environment.\n")
string(APPEND _doc "- `configure.bat` selects a configure preset and generates that build directory.\n")
string(APPEND _doc "- `generate_project.bat` runs CMake preset generation directly.\n")
string(
    APPEND
    _doc
    "- `build.bat` builds the original Doom 3 Win32 layout by default: `Doom3.exe` and `DedServer.exe` in the repository root, and `base/gamex86.dll` in the base folder.\n\n"
)

string(APPEND _doc "## Install And Export\n\n")
string(
    APPEND
    _doc
    "- `ninja-install-sdk` configures an installable SDK prefix with runtime binary installation disabled for source-light package validation.\n"
)
string(APPEND _doc "- The installed SDK exports `IdTech4::SDK` through `lib/cmake/IdTech4/IdTech4Targets.cmake`.\n")
string(
    APPEND
    _doc
    "- `IdTech4Config.cmake` and `IdTech4ConfigVersion.cmake` support downstream `find_package(IdTech4 CONFIG REQUIRED)` projects.\n"
)
string(
    APPEND
    _doc
    "- SDK install components include idLib headers, Curl headers, CMake helper modules, presets, dependency manifests, and generated/source documentation.\n"
)
string(
    APPEND
    _doc
    "- Full runtime install rules are available through `IDTECH4_INSTALL_RUNTIME_TARGETS=ON` for builds that produce the engine binaries and libraries.\n\n"
)

string(APPEND _doc "## CPack Packages\n\n")
string(
    APPEND
    _doc
    "- SDK package presets include `ninja-sdk-zip`, `ninja-sdk-stgz`, `ninja-sdk-deb`, `ninja-sdk-rpm`, `ninja-sdk-nsis`, and `ninja-sdk-wix`.\n"
)
string(
    APPEND
    _doc
    "- ZIP, DEB, RPM, and STGZ package generation works from the SDK component path; NSIS and WiX require their external installer toolchains.\n"
)
string(
    APPEND
    _doc
    "- Package names include the sanitized `git describe --tags --dirty --always` label stored in `IDTECH4_VERSION_LABEL`.\n\n"
)

string(APPEND _doc "## Formatting And Linting\n\n")
string(APPEND _doc "- `.clang-format` defines the C/C++ style for modern test and package fixtures.\n")
string(APPEND _doc
       "- `.cmake-format.yaml` defines CMake script formatting and lint behavior for the modern build-system files.\n"
)
string(
    APPEND
    _doc
    "- `.pre-commit-config.yaml` wires clang-format, cmake-format, cmake-lint, YAML checks, trailing whitespace, and EOF checks.\n"
)
string(APPEND _doc "- `ninja-format-check` runs the non-mutating formatter checks through CMake.\n")
string(APPEND _doc "- `ninja-format` applies clang-format and cmake-format to the enforced file set.\n\n")

string(APPEND _doc "## Multitoolchain Support\n\n")
string(APPEND _doc
       "- `cmake/IdTech4Compiler.cmake` applies target-based compiler profiles for MSVC, Clang, GCC, and Emscripten.\n"
)
string(APPEND _doc "- Clang presets enable the extra diagnostic profile intended for best local diagnostics.\n")
string(APPEND _doc "- GCC presets cover Linux-style Debug, Release, and test builds.\n")
string(APPEND _doc
       "- MSVC support is provided by the Visual Studio 2026 presets and the Windows CI MSVC developer shell.\n"
)
string(
    APPEND
    _doc
    "- `emscripten-smoke` disables native engine targets and builds `idtech4_emscripten_smoke` as a WebAssembly toolchain proof.\n\n"
)

string(APPEND _doc "## CI Targets\n\n")
string(APPEND _doc "- `idtech4_tests` builds GoogleTest, Catch2, and integration artifact checks.\n")
string(APPEND _doc "- `idtech4_build_system_docs` creates this generated build-system documentation.\n")
string(APPEND _doc "- `idtech4_api_reference` generates the Doxygen HTML API reference when Doxygen is enabled.\n")
string(APPEND _doc "- `idtech4_docs_site` assembles the deployable GitHub Pages documentation site.\n")
string(APPEND _doc "- `idtech4_generate_docs` aggregates the build docs, API reference, and site generation targets.\n")
string(APPEND _doc "- `idtech4_binary_size` emits a binary-size report for CI artifact tracking.\n")
string(APPEND _doc "- `idtech4_ci_package` stages build outputs and documentation into a zip artifact.\n")
string(APPEND _doc
       "- `idtech4_coverage` runs CTest and collects gcov or llvm-cov output, depending on the active preset.\n\n"
)

string(APPEND _doc "## Documentation Deployment\n\n")
string(APPEND _doc
       "- `ninja-docs-site` configures Doxygen as required and builds `build/cmake/ninja-docs-site/docs/site`.\n"
)
string(APPEND _doc
       "- The documentation site contains a generated landing page, repository docs, and `api/index.html`.\n"
)
string(
    APPEND _doc
    "- `.github/workflows/pages.yml` publishes that site to GitHub Pages on `main`, `master`, or manual dispatch.\n\n"
)

string(APPEND _doc "## Artifact Layout\n\n")
string(
    APPEND
    _doc
    "CI package archives contain `bin/`, `lib/`, `docs/generated/`, `docs/source/`, and `manifest.txt` entries. Runtime game data is intentionally not bundled by this build-system artifact target.\n"
)

file(WRITE "${OUTPUT_FILE}" "${_doc}")
message(STATUS "Build-system documentation written to '${OUTPUT_FILE}'.")
